---
title: "Gov 50 Final Project"
author: "Sam Church"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in doing my final project on an issue related to the federal court system. For example, I'd be interested in exploring how Chevron Deference has been declining as the justification in recent court decisions.

##Project Proposal

Does the Supreme Court defer more to certain executive agencies over others when questions of statutory interpretations arise? In this report, I will attempt to determine whether the Supreme Court favors certain executive agencies when applying the doctrine of Executive Deference. I hypothesize that the supreme court applies deference relatively equally among executive agencies, as the doctrine of deference does not discriminate between the roles of distinct agencies. Thus, when examining data about whether or not the Supreme Court sides with an executive agency in a decision, I expect each agency to have a similar win rate in cases revolving around deference. The explanatory variable of interest my project will focus on is the agency bringing a case invoking the deference doctrine before the Supreme Court. The outcome variable would be the win rates of those different agencies when those cases are brought before the court. Thus, the database I will be utilizing is a list of Supreme Court cases from 1984 to 2019 where an agency attempts to interpret a law (statutory interpretation). If the the difference in win rates between different agencies is not statistically significant, my hypothesis would have been found to have statistical report. If there are statistically significant differences in win rates of agencies, there would appear to be favoritism on the Supreme Court, and my hypothesis would be disproven.

The variable for agency is coded 0-52, with each representing a different executive agency bringing the case to the Court. The variable called favors_agency can be considered in determining win rate. It is coded as a 0 if the decision favors agency, 1 if it does not, and 2 if it was mixed. To minimize confounding factors, I will only consider a 2 as a win for an agency. 

In addition, to avoid confounding variables regarding other aspects of cases, I will only investigate cases where the court determined Chevron Deference (one of the deference doctrines) should apply. Thus, the only cases I will evaluate are ones where Chevron Step 0 (does the Chevron framework apply) is coded as a 1 to indicate yes.

Link to dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZNCKL5



